refactor(final_step): add code climate badge for maintainability
AlexMomot-717/python-project-83 pull request #7
Opened 2024-02-12 04:51 UTC by AlexMomot-717

2024-02-19 17:56 UTC, svntmr requested changes
looks like we can remove some debug-related changes

2024-02-19 17:56 UTC, svntmr commented on page_analyzer/app.py
> +    return render_template("index.html", url_name=url_name)
what is the reason for this change?

2024-02-19 17:56 UTC, svntmr commented on page_analyzer/templates/base.html
> +            <li class="nav-item"><a class="nav-link" href="/urls">Сайты</a></li>
is it possible to return `url_for` back?

2024-02-19 17:56 UTC, svntmr commented on page_analyzer/templates/url.html
> +    <form method="post" action="/urls/{{ url.id }}/checks">
is it possible to return `url_for` back?

2024-02-19 17:56 UTC, svntmr commented on page_analyzer/templates/urls.html
> +              <a href="/urls/{{ url.url_id }}">{{ url.url_name }}</a>
is it possible to return url_for back?

2024-02-20 02:46 UTC, AlexMomot-717 commented on page_analyzer/app.py
> +    return render_template("index.html", url_name=url_name)
the reason is to keep incorrect url value in the url input field

2024-02-20 02:46 UTC, AlexMomot-717 commented on page_analyzer/app.py
> +    return render_template("index.html", url_name=url_name)
![Снимок экрана от 2024-02-20 08-45-50](https://github.com/AlexMomot-717/python-project-83/assets/76219029/0c148068-0c35-45a3-82f6-d7353e641d1f)

2024-02-20 06:09 UTC, svntmr approved these changes
one small thing that can be improved, but LGTM otherwise!

2024-02-20 06:09 UTC, svntmr commented on page_analyzer/app.py
> +    return render_template("index.html", url_name=url_name)
wdyt, does it make sense not to pass it here and fetch value for this field from the flash messages in the view instead? or make it optional - so you'll pass it only when needed

2024-02-20 13:50 UTC, merged